baseURL = '/'
languageCode = 'en-us'
title = ''
theme = 'LoveIt'

[taxonomies]
  category = "categories"
  tag = "tags"

[author]
name = "Alan"
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
  [[menu.main]]
    weight = 2
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

[params]
defaultTheme = "light"
title = ""

[params.header.title]
name = "TechTrajectory"

[params.page.share]
enable = false

[params.footer]
enable = true
author = true
hugo = false
since = 2023

[params.home.profile]
title = "TechTrajectory"
subtitle = "Explore the dynamic landscape of technology with TechTrajectory. This blog offers a unique perspective on the ever-evolving tech world, shedding light on the intricacies of system design and the latest innovations."
typeit = false

[markup.goldmark.renderer]
unsafe = true